import Header from './components/Header'
import NavBar from './components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">     
      <body className={inter.className}>
       <Header logoSrc={"https://lemonagency.com/wp-content/uploads/lemon_logox400.png"} navItems={[{label:"about", url:"/"},{label:"work", url:"/"},{label:"services", url:"/"}]}/>
        {children}</body>
    </html>
  )
}
